ticksUntilDeath = 2400
continueTimerWhileOffline = false
rescueActionTicks = 40
rescueRespawnHealth = 5
rescueRespawnFoodLevel = 5
rescueRespawnEffects = ["minecraft:hunger|600|0", "minecraft:weakness|1200|0"]
rescueDistance = 10.0
glowOnKnockout = true
allowUnarmedMelee = true
allowBows = false
allowPistols = false
